### ISSUE TITLE
Vlad.faceapi.matchFaces vs Vlad.human.match faces performance issue

### ISSUE THREAD

**Issue by okeoke85** [vladmandic/human#100]
Hi Vlad, for consisteny i just want to use only vlad.human, i have the impression of vlad.human includes vlad.faceapi functionality i'm testing both of them, vlad.faceapi giving me more accurate results i will give data and code below to make the case again, is these normal results? If so i will be enforced to use vlad.faceapi, or some configuration or control issue, thanks in advance.

HumanInstance.config;

let HumanInstance = new humanapi.Human({
    videoOptimized: false,
    backend: "webgl",
    modelBasePath: "/app/humanapi/models",
    face: {
        enabled: true,
        detector: { rotation: true, return: true },
        mesh: { enabled: true },
        description: { enabled: true },
        embedding: { enabled: true }, // alternative you can use embedding module instead of description
    },
});

Images,

![image](https://user-images.githubusercontent.com/15729538/114485413-8a63b000-9c14-11eb-91e3-a8e1b244336d.png)

**Vlad.Human result;**

Result:
Similarity score between two faces as %46(Similarity : 0.4620827498176056) so i cant accept these two as same, but they are actually same.

Code:

```
      let baseImageDetection: any = await HumanInstance.detect(baseImage);
      let imageDetection: any = await HumanInstance.detect(image);
      let similarity = HumanInstance.similarity(baseImageDetection.face[0].embedding, imageDetection.face[0].embedding);
```

**Vlad.Faceapi result;**

Result:
Best match : {"_label":"person 1","_distance":0.40438607584877767}, tolarance value is 0.6 the logic is ; if distance > 0.6 no-match

Code:

```
let faceMatcher = new faceapi.FaceMatcher(baseImageDetection, 0.6);
let bestMatch = faceMatcher.findBestMatch(imageDetection.descriptor);
console.log(`Best match : ${JSON.stringify(bestMatch)}`);
```

**Comment by vladmandic** [comment]
1. you have both `description: { enabled: true }` and `embedding: { enabled: true }` - it should be one or the other. can you test with both separately and see what your results are? `description` model is newer, but since it's still being tuned, i've left older `embedding` model still available.
2. matching is a hit&miss - sometimes it's better, sometimes it's worse. do you have a larger dataset so i can run additional analysis?
3. i have several additional pre-processing functions ready in the code, but disabled as i don't want to expose users to too many variables. again, if you can share your dataset of facial images, i can try different options.

**Comment by okeoke85** [comment]
I just have these two images as dataset, i'm not training a model if u ask, you can find images below
![image](https://user-images.githubusercontent.com/15729538/114490216-1b3e8980-9c1d-11eb-9c99-7a765cf67e39.JPG)
![base-image](https://user-images.githubusercontent.com/15729538/114490218-1bd72000-9c1d-11eb-92a9-efa7dbe0835e.JPG), how can i use decriptors in human, i can see it in faceapi but not human, 
maybe i should take similarity score lower?

**Comment by vladmandic** [comment]
> how can i use decriptors in human, i can see it in faceapi but not human, maybe i should take similarity score lower?

not sure what you mean?

anyhow, just by changing one constant in `simmilarity` function and testing on your two photos, i got default 49% then down to 36% then up to 61% - but relative simmilarity between 200 faces in my test dataset does not change. so that simmilarity percentage is just a number, cannot be directly compared to `face-api`. question is does it get higher number for correct faces than incorrect ones - so score between your two photos is almost irrelevant - need to have bigger number of images to see if they get correct scores by simmilarity so they can be sorted accordingly.

also, then i tried some pre-processing tricks - by changing how aggressive cropping on the face is, i can get better results from the model, but then some other faces get distorted or incorrectly cropped.

there are also additional colorization and contrast tricks that can improve overal detection which i've implemented, but it requires a lot of manual verification to figure out which values are best to use.

last i tried reducing complexity of the descriptor from 1024 element array to only 128 elements and the simmilarity jumped all the way to 88%

and that is without even going into model training, that's just a) tweaking math, b) tweaking image pre-processing

that's why honestly i hate dealing with feature vectors directly - it's so easy to manipulate results that it takes forever to tune it.

you can take a look at simmilarity math at `src/faceres/faceres.ts:simmilarity()` and image pre-processing at `src/faceres/faceres.ts:enhance()`

and a pretty detailed demo is as `demos/facematch.html` & `demos/facematch.js`

**Comment by okeoke85** [comment]
In my case only dataset is base image, and vlad.faceapi gives me good results with threshold comparance, maybe you can include this logic to human as well, i mean if i give another person's image it gives me a distance lower than threshold. I understand similarity logic as you described i guess similarity only good for datasets, thank you for detailed help.

**Comment by lghasemzadeh** [comment]
> In my case only dataset is base image, and vlad.faceapi gives me good results with threshold comparance, maybe you can include this logic to human as well, i mean if i give another person's image it gives me a distance lower than threshold. I understand similarity logic as you described i guess similarity only good for datasets, thank you for detailed help.

Hello @okeoke85,
I opened an issue in your ADEBAProjectWinForm repository, I would appreciate if you answer.
Thank you
