### ISSUE TITLE
Uncontrolled model import of human

### ISSUE THREAD

**Issue by okeoke85** [vladmandic/human#101]
Hi Vlad,

I'm trying to understand the model load vlad.human, in vlad.faceapi i can control the loads of models like below,

```
// Promise.all([
//     faceapi.nets.faceRecognitionNet.loadFromUri("/app/faceapi/models"),
//     faceapi.nets.faceLandmark68Net.loadFromUri("/app/faceapi/models"),
//     faceapi.nets.ssdMobilenetv1.loadFromUri("/app/faceapi/models"),
// ]);
```

In human even i create new instance without config i see some network request to load models, like below, the weird thing requests goes to /app/faceapi/models path even human doesnt know about this path at all.

like this network request;

![image](https://user-images.githubusercontent.com/15729538/114523107-abe08e00-9c4c-11eb-85f1-0e0e730bcbfc.png)

```
import * as faceapi from '@vladmandic/face-api';
import * as humanapi from '@vladmandic/human'
let HumanInstance =  new humanapi.Human();
```

Best.

**Comment by vladmandic** [comment]
`face_recognition_model.*` are part of `face-api`, not `human`, but browser inspector is misleading that call is coming from `human` because that's where `tfjs` is embedded and `fetch` is triggered by `loadGraphModel()` function inside `tfsj`

in your case, you're loading `human.esm` and `face-api.esm` which both embed `tfjs`, but there can only be one active instance of tfjs on the system. 

when using concurrent multiple libraries that use `tfjs`, to be gramattically correct, you should load `tfjs` manually and use `-nobundle` versions of `human` and `face-api`.
(at least have just one with embedded `tfjs` and the other without.)

**Comment by okeoke85** [comment]
Thank you Vladamir, i ll switch to no-bundle versions as you said.
