### ISSUE TITLE
demo not working

### ISSUE THREAD

**Issue by lghasemzadeh** [vladmandic/human#115]
![Screenshot from 2021-04-25 20-33-00](https://user-images.githubusercontent.com/36885164/116003146-7bfa9880-a605-11eb-9612-4ac1cc6d1dfb.png)
Hi Vladimir,

I followed the structure you wrote me before, but I still get error and can not install.
But I was able to install it on my friend's laptop (I think there is sth wrong with my pc), now I wanted to run it as I was previously doing but it is not working anymore.
I just want to see the demo as before. In vs code, activating the 'Go live' and selecting the demo. page opens, camera activated but no stream/video, no output. 

I updated and install it again but did not work.
Any idea?

thx

**Comment by vladmandic** [comment]
*"Go Live"* is not a VSCode feature, it's a feature of some plugin installed in VSCode that creates a live web server - and I have no idea how that plugin works since it could be any number of them.

Can you use dev web server that ships with `Human` instead? It's fully documented.

And if there are issues with browser, would be good to get a log from browser inspector, not just a screenshot.

My best guess is that a "live server" that a plugin created is not a fully functional one or it references a wrong root path so page fails on loading models, but since there is no log, I really can't tell.

**Comment by vladmandic** [comment]
closing as no user feedback and issue is not library related.

**Comment by lghasemzadeh** [comment]
I just restart the system and then it worked. 
I think there were several files processing in the queue and the browser cache was engaged, that is why it was not working and after restarting the problem was resolved.
