### ISSUE TITLE
Webworker Configuration

### ISSUE THREAD

**Issue by mainisameer** [vladmandic/human#126]
**Issue Description**
We are using React for FE and trying to  implement Human as a web worker, it does the detection while you are on the webpage. But if you move to another tab the detection stops. While I understand that this may be a web worker /browser behavior, I was wondering if someone had implemented a way to lower the priority but still keep the detection on so we can out the data for other application. 
Our goal is to lower the CPU utilization at the end computer.

**Comment by vladmandic** [comment]
enforcement of background tabs activity is up to browser with no way to control it from the client page.  
for example, chrome has two features, `tab-freeze` and `intensive-wake-up-throttling`.

now, in theory, the execution in web worker does not get suspended, but the problem is that timers do not fire when tab is in the background. so possible solution would be to trigger processing of the next frame from main thread by listening for worker's `onmessage` events - when it receives a message that one frame is complete, immediately trigger a next frame (without ever using `setInterval` or `setTimeout`, or `requestAnimationFrame` or anything like that as they will be suspended).

another thing to experiment with is add elements to main thread that are not subject to throttling (but google changes that list sometimes). for example, if page is playing audio, it may be considered as foreground even if you navigate out of tab. or if application is using websockets or webrtc for real-time communication - again, chrome will not suspend tabs using websockets or webrtc (so things like chats or your video calls don't get disconnected when you switch tabs).

but that's about it - two ideas worth a shot.

(i'm really not sure how firefox or safari handle this as i did not study it in details)

now, if the goal is simply to reduce cpu load, you can slow down detection - instead of using `requestAnimationFrame` to run detection as fast as possible, you can add a `setTimeout` with a delay before starting processing of the next frame.

**Comment by mainisameer** [comment]
Thank you.. we knew this wasn’t a question directly related to the ApI so
appreciate your guidance on it. The page is using WebRtc and web socket so
not sure why it would not get a response from web worker ... more research
to be done...

**Comment by vladmandic** [comment]
now i'm curious - if you're using webrtc, then tab in background should remain flagged as active.
take a look at `chrome://discards` - what does it say about that tab when is it in the background?

also, is it `onmessage` that is not getting triggered or is it that next frame never starts becaues timer does not get triggered?

**Comment by mainisameer** [comment]
Will have answers shortly from someone who is more qualified than me at this..:)

**Comment by mainisameer** [comment]
Issue is resolved, it was the way we are trying to access the video
element. Thank you for all you help
