### ISSUE TITLE
Object detection for phone

### ISSUE THREAD

**Issue by okeoke85** [vladmandic/human#127]
**Cell Phone  or Cell Phone usage  detection**

Hi Vladamir, actually this is a question, my goal is to find out a person is using his cell-phone in image effctively, time to time i can get the phone detection but it must be very clear in image, for example can i detect if a person is talking to with phone while holding phone close to his ear like,  thanks in advance.

Best.

```
    let imageDetection = await HUMAN_API.detectHuman(tensor);
    console.log(JSON.stringify(imageDetection.object));
```

**Comment by vladmandic** [comment]
coco dataset does have `mobile phone` class, but i doubt that lightweight and quantized version of **centernet with mobilenet v3 ltie** object detection model included in `human` can reliably detect semi-hidden phones, it's just too lightweight (i cannot include larger & better models because of performance and size restrictions i've placed on `human` library). you can try, but i doubt it would be reliable at all.

but then they question is where are you running detection itself? if it's on a mobile phone or any device with limited resources, then you cannot really use a better model as they are really gpu and memory intensive. for example, my favorite coco model is **centernet based on reset50 v2** - but that model is 130MB just weights and requires 500-800MB of GPU RAM to run reliably.

ideally, you can take lightweight mb3-centernet and retrain it for your specific purpose - but that only works if you have a quality set of sample images to train with. and it has to be large enough and fully annotated (with boxes).

otherwise, you could try some math-based analysis - face + body + hand and calculate what is the chance that person is holding a phone if he's in a specific pose.

**Comment by vladmandic** [comment]
actually, i just tried with `mb3-centernet` in `human` and results for cell phone detections are not bad.
average score for cell phone detection is ~20% as model is not that precise and if scene is busy, it may drop out of detected objects as there are others with higher score.

but it's easy to modify `src/object/centernet.ts:process()` function to either bump of scores for cell phone (example: `if (classVal === 67) score = Math.min((score * 2), 1);
`) or skip NMS analysis and filter just for it ignoring rest of results processing.

**Comment by okeoke85** [comment]
May i use it by myself or do you need to update npm package fo mb3-centernet

**Comment by vladmandic** [comment]
it's included in `human` v2
