### ISSUE TITLE
WASM backend files missing

### ISSUE THREAD

**Issue by ButzYung** [vladmandic/human#132]
In previous version of `human`, the files needed for WASM backend (e.g. `tfjs-backend-wasm.wasm`) are located in `assets` folder. However, these files have been missing since a certain version (I noticed it before but I supposed it was a temporary issue). I can get the files from `tensorflow` dependency folder, but I don't think this is how the library is supposed to work.

**Comment by vladmandic** [comment]
I've removed it a while ago and:
- updated built-in dev server
- updated default `wasmPath: '../node_modules/@tensorflow/tfjs-backend-wasm/dist/'`
- updated all demos to download WASM from CDN: `  wasmPath: 'https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-backend-wasm@3.7.0/dist/'`.

Reason was two-fold - reduce size of the bundle, but more importantly due to change in Chrome 90 where it started throwing errors due to web server requirement for a specific header in order to be allowed to load WASM binaries.

Built-in dev server was updated to be fully compliant, but I had too many users reporting issues with their own web servers, so it was easier to update demo paths to use CDN location than explain again and again how web server must be properly configured.

I'm open to include WASM binaries in `/assets` if you have a valid reason?

**Comment by ButzYung** [comment]
Oh sorry I wasn't aware that the default path changed too (I manually pointed the path to the `assets` folder). If we can use the exact same files from the official tensorflow build, that's perfectly fine I suppose.

**Comment by ButzYung** [comment]
Or maybe you can update the info for configuration, and inform the users that they can mnually download the files from the above CDN, since not everyone using this library would need to install the dependencies (thus no `node_modules` folder)

**Comment by vladmandic** [comment]
I agree on doc updates, but as it's non-critical it will have to wait for a bit as I'm traveling for the next few weeks.

**Comment by vladmandic** [comment]
updated <https://github.com/vladmandic/human/wiki/Backends> and closing this issue
