### ISSUE TITLE
YOLOv5_Face

### ISSUE THREAD

**Issue by MariasStory** [vladmandic/human#139]
Hi @vladmandic,
Congradulations on the cool solution. Please concider implementing the YOLOv5_Face model that was so kindly converted by @PINTO0309:
https://github.com/PINTO0309/PINTO_model_zoo/tree/main/130_YOLOv5_Face

**Comment by vladmandic** [comment]
I'll take a look at it when I'm back in ~10 days.

**Comment by vladmandic** [comment]
first, model relies on `ResizeNearestNeighbor` kernel op which is not yet implemented in WASM backend, so it can only be used in NodeJS and Browser with WebGL.
issue is open with tfjs, see <https://github.com/tensorflow/tfjs/issues/4766>

kernel ops used by model:

```json
2021-07-30 07:44:08 INFO:  graph model: /home/vlado/dev/yolo-face/model/5s-large/model.json
2021-07-30 07:44:08 INFO:  size: { unreliable: true, numTensors: 169, numDataBuffers: 169, numBytes: 28260768 }
2021-07-30 07:44:08 DATA:  ops used by model: {
  graph: [ 'Const', 'Placeholder', 'Identity', [length]: 3 ],
  transformation: [ 'Pad', 'Reshape', [length]: 2 ],
  convolution: [ 'Conv2D', 'MaxPool', [length]: 2 ],
  arithmetic: [ 'Add', 'Mul', [length]: 2 ],
  basic_math: [ 'Sigmoid', [length]: 1 ],
  slice_join: [ 'ConcatV2', [length]: 1 ],
  image: [ 'ResizeNearestNeighbor', [length]: 1 ],
  matrices: [ 'Transpose', [length]: 1 ]
}
```

second, model output is strided and code that decodes it is really messy (i wish there was a simple reference implementation with post-processing, but <https://github.com/deepcam-cn/yolov5-face/blob/master/detect_face.py> relies on too many external functions at the moment). i could reverse engineer it, but since it wouldn't work with WASM at the moment, it's not worth it.

```json
2021-07-30 07:44:08 INFO:  graph model: /home/vlado/dev/yolo-face/model/5s-large/model.json
2021-07-30 07:44:08 DATA:  outputs: [
  { id: 0, name: 'Identity_1', dytpe: 'DT_FLOAT', shape: [ 1, 46, 80, 16, 3, [length]: 5 ] },
  { id: 1, name: 'Identity_2', dytpe: 'DT_FLOAT', shape: [ 1, 92, 160, 16, 3, [length]: 5 ] },
  { id: 2, name: 'Identity', dytpe: 'DT_FLOAT', shape: [ 1, 23, 40, 16, 3, [length]: 5 ] },
]
```

all-in-all, interesting model, but not a candidate at the moment. will revisit in the future.
