### ISSUE TITLE
Add NudeNet and NSFWJS models

### ISSUE THREAD

**Issue by scratcher28** [vladmandic/human#151]
Hi, Vladimir. Could you, please, add support for vladmandic/nudenet and infinitered/nsfwjs models to HumanJS?

**Comment by vladmandic** [comment]
`vladmandic/nudenet` is simply too large and slow to be included in `human` directly  
`infinitered/nsfwjs` is smaller and faster (3.1mb or 2.1mb depending on variation), but use-case is much more limited  

in theory, i could add support and leave it as hidden and require user to provide model weights (instead of pre-packaging them with human), but...  
given that both models work on full image input, there is no real advantage of `human` pipeline (e.g., it doesn't require special pre-processing or cropping or anything)  
so why not just execute them sequentially (before or after `human` detect)? that is what i do in my own projects that perform multi-model work

**Comment by scratcher28** [comment]
Since I am using all 4 libraries, the main advantage could be the increase the performance and reducing the code base.

**Comment by vladmandic** [comment]
there wouldn't be more than <1% performance advantage and that would come only from input -> tensor processing  
and you can already use `human` for that and then pass tensor to `nudenet` and/or `nsfwjs`

**Comment by scratcher28** [comment]
Do you have any examples how to do that?

**Comment by vladmandic** [comment]
explicitly call `human.image()` so you can keep the results (that's what `human.detect` does internally but if input to `human.detect` is a tensor, it will use it as-is and skip processing as it assumes its already done by user):

```js
const processed = await human.image(input, myConfig); // input is any supported input type
const res1 = await human.detect(processed.tensor, myConfig); // human.detect will now use provided tensor as-is
const res2 = await someOtherModel.predict(processed.tensor);
human.tf.dispose(processed.tensor); // since you called it explicitly, now you have to dispose it explicitly as well otherwise its done automatically
```

**Comment by vladmandic** [comment]
i'm happy to help with your implementation further, but closing this issue as `will-not-fix` as those two models will not be included in `human` at this time.
