### ISSUE TITLE
rebuild TensorFlow with the appropriate compiler flags

### ISSUE THREAD

**Issue by kzpromo** [vladmandic/human#153]
Vladimir, i recive errors in my nodejs project on start

```
Uncaught (in promise) Error: Kernel 'RotateWithOffset' not registered for backend 'tensorflow'
    at Engine.runKernel (engine.ts:548)
    at rotateWithOffset_ (rotate_with_offset.ts:58)
    at Object.rotateWithOffset__op [as rotateWithOffset] (operation.ts:51)
    at HandPipeline.estimateHands (/Users/../Documents/.././node_modules/@vladmandic/human/dist/human.node.js:7901)
    at async predict5 (/Users/../Documents/../../node_modules/@vladmandic/human/dist/human.node.js:7958)
    at async /Users/../Documents/../../node_modules/@vladmandic/human/dist/human.node.js:11687
```
![Снимок экрана 2021-08-12 в 16 37 04](https://user-images.githubusercontent.com/10184174/129183756-d765dec2-80db-46f1-a54a-8913dde6d670.png)

My env MacOs Mojave 10.14.6

In shell i recive this message
_2021-08-12 16:31:55.639249: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags._

Example of my code

```
const tf = require('@tensorflow/tfjs-node');
const path = require("path"); 
const Human = require('@vladmandic/human/dist/human.node.js').default;


let human = null;

const myConfig = {
    backend: 'tensorflow',
    modelBasePath: path.join(process.cwd(), 'models'),
    debug: true,
    async: false,
    filter: {
        enabled: true,
        flip: true,
    },
    face: {
        enabled: true,
        detector: { enabled: true, rotation: false },
        mesh: { enabled: true },
        iris: { enabled: true },
        description: { enabled: true },
        emotion: { enabled: true },
    },
    hand: {
        enabled: true,
    },
    // body: { modelPath: 'blazepose.json', enabled: true },
    body: { enabled: true },
    object: { enabled: true },
};

async function init() {
    // create instance of human
    human = new Human(myConfig);
    // wait until tf is ready
    await human.tf.ready();
    // pre-load models
    console.log('Human:', human.version);
    console.log('Active Configuration', human.config);
    await human.load();
    const loaded = Object.keys(human.models).filter((a) => human.models[a]);
    console.log('Loaded:', loaded);
    console.log('Memory state:', human.tf.engine().memory());
}
async function main() {
    await init();
}
main();


async function detectVideo() {
    // select input HTMLVideoElement and output HTMLCanvasElement from page
    // perform processing using default configuration
    human.detect(preview).then((result) => {
        // result object will contain detected details
        // as well as the processed canvas itself
        // so lets first draw processed frame on canvas
        human.draw.canvas(result.canvas, canvas);
        // then draw results on the same canvas
        human.draw.face(canvas, result.face);
        human.draw.body(canvas, result.body);
        human.draw.hand(canvas, result.hand);
        human.draw.gesture(canvas, result.gesture);
        // and loop immediate to the next frame
        requestAnimationFrame(detectVideo);
    });
}
```

how to fix this

**Comment by kzpromo** [comment]
и еще вопрос, как определять положение лица, типа голова повернута в право или лево
смотрит в право или лево

**Comment by vladmandic** [comment]
@kzpromo english please, i cannot read this.

**Comment by kzpromo** [comment]
> @kzpromo english please, i cannot read this.

sorry, I thought you understand Russian
i updated the text

**Comment by vladmandic** [comment]
> Uncaught (in promise) Error: Kernel 'RotateWithOffset' not registered for backend 'tensorflow'

known limitation due to missing operation in `tfjs-node`, disable hand rotation `myConfig.hand.rotation = false`  
see <https://github.com/vladmandic/human/blob/main/TODO.md#hand-detection> for details  
should be implemented in the next version  

but...It also means that in your example, app cannot auto-detect if this is browser or node environment  
(because if it's not browser, it should auto-disable rotation since this is a known limitation)

what is also strange is that you're using functions like `requestAnimationFrame` which is browser-only  
so what exactly is your environment?  
it auto-detects as browser, but uses `tfjs-node`??

> This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations: AVX2 FMA
> To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags

annoying info message from `tensorflow`, but cannot be suppressed. There is nothing wrong, it says that optimization is enabled for all critical operations (as it should be) and not enabled otherwise (as it shouldn't be)  

btw, I don't build `tensorflow` binaries (since I'd need to build for quite a lot of different platforms separately),  
they come included inside `tfjs-node` package  
(i do on the other hand build JS tensorflow libraries since they are platform independent)

>and another question of how to determine the position of the face, such as the head is turned to the right or to the left
looks to the right or to the left  

that is part of gesture recognition and is enabled by default  
see <https://github.com/vladmandic/human/wiki/Gesture> for details  

> sorry, I thought you understand Russian

i'm Croatian :)

**Comment by kzpromo** [comment]
thank you! it works!

**Comment by vladmandic** [comment]
glad it worked, but i'd like to understand why auto-detect didn't pick it up?
see my previous comments below...

> It also means that in your example, app cannot auto-detect if this is browser or node environment
> (because if it's not browser, it should auto-disable rotation since this is a known limitation)

> what is also strange is that you're using functions like `requestAnimationFrame` which is browser-only
> so what exactly is your environment? it auto-detects as browser, but uses tfjs-node??
