### ISSUE TITLE
Memory leak running human in latest Chromium

### ISSUE THREAD

**Issue by ButzYung** [vladmandic/human#181]
There is a serious memory leak running `human` on newer versions of Chromium-based browser (including `electron` which uses the same browser engine), and Firefox. I can confirm that Chromium v93 and above is affected. When running `human`, the GPU memory usage keeps on increasing untill all GPU memory is occupied, and then the CPU memory usage will increase as well, until it finally crashes.

I discovered this issue when I updated `electron` during the testing of my app which uses `human`, and I confirmed that it only affected Chromium v93+ (not sure about v92 but at least things did work properly on v91). My app use various Tensorflow-based modules including `human`, TFJS and Mediapipe, and at first I thought it was a general Tensorflow-based issue when using WebGL backend, but upon more testings, I can confirm that `human` is the only source of problem here, regardless of whether it's WebGL or WASM backend, worker or not. In fact, the simplest way to reproduce this issue is to run the default `human` demo.

https://vladmandic.github.io/human/demo/index.html

PS: I am testing these on a Windows 10 (21H1) 64-bit platform, just in case it's platform-dependent.

**Comment by vladmandic** [comment]
i spent a lot of time on that, its not a leak in `human` but a bug in `webgl` implementation in **chrome**  
affected are: chrome 93, 94, 95. older or newer versions work fine  

i've documented it at #167

**Comment by ButzYung** [comment]
But things do work when it's just TFJS. Like in my case, things work when I run the TFJS Facemesh, instead of `human` Facemesh. Maybe  this difference gives some hints on how this problem can be avoided (instead of waiting for the browser side to fix it)?

**Comment by vladmandic** [comment]
its not a leak, its gpu buffering done by chrome - massive bug  
and problem is the same, just effects are different on `wasm` and `webgl` backends  

i just tried to verify:

- chrome 94 on windows 11: gpu memory rises slowly until it occupies all available memory  
  with wasm backend, that is non fatal since it doesnt need gpu memory
  with webgl backend, that is fatal since it runs into oom.

- chrome 96 on windows 11: gpu memory does not rise. its constant regardless of backend.

**Comment by ButzYung** [comment]
Good to know it seems to be fixed on Chrome 96 at least

**Comment by vladmandic** [comment]
yup. also, it seems to be related to canvas draw, nothing to do with tfjs  
so if you capture webcam input and draw it to canvas in a loop you get the same problem  

so running human demo like this <https://localhost:10031/?backend=wasm&async=false&worker=false> has the same problem, but memory growth is much slower simply since redraw is much slower.

**Comment by vladmandic** [comment]
closing the issue as external
