### ISSUE TITLE
Python backend part api with human.js

### ISSUE THREAD

**Issue by shurshilov** [vladmandic/human#254]
Not bug just question for help.
I need comapre descriptors on python side 
a rewrite similarity,normalizeDistance,distance functions its easy
NOW i need translate base64 store DB descriptor to python for work
In js i use                 
```
this.descriptor_ids = [];
for (var f32base64 of data.descriptor_ids) {
    thus.descriptor_ids.push(new Float32Array(new Uint8Array([...atob(f32base64)].map(c => c.charCodeAt(0))).buffer))
}
```
And compare like  with human js
```
const found = result.face[0].embedding
const similarity = this.parent.human.similarity(Array.from(this.descriptor_ids[i]),found);
```
similarity anlog I have. But how convert descriptor base64 to use in python have idea?

**Comment by vladmandic** [comment]
i'd rather normalize descriptors from `f32` to `uint16` - just multiply by a factor and truncate - much simpler and you can continue with those values directly in python.  

(i do that anyhow when i want to store large number of descriptors in a database as storage requirements for uint16 are half of f32. and for extreme, you could even go with uint8, but that does result in some loss of precision.)

**Comment by vladmandic** [comment]
> How can i chech in js that Human already loaded?

Depends what do you mean by *loaded*?  
- If you want to check if models are loaded, simply check `human.models` - it exists exactly for that purpose, its a key/value object that will tell you which models are loaded.
- If you want to check if instance is warmed up and ready for inference, subscribe to events and `human` will tell you when warmup is complete. For example, `human.events.addEventListener('warmup', () => log.info('warmup complete'));`

> And wgy on HTTPS in chrome now i get error? `ERR_HTTP2_PROTOCOL_ERROR`

Human does not implement low-level HTTP protocol, that is up to browser. And this specific error happened couple of times in the past, always because some temporary incompatibility between *browser*, *OS* and *web server*.

Examples for each:
- Chrome bug: <https://chromium-review.googlesource.com/c/chromium/src/+/2001234>
- NGINX web server issue: <https://stackoverflow.com/questions/60974237/chrome-neterr-http2-protocol-error-200-after-a-reconnect>
- Windows bug: <https://support.microsoft.com/en-us/topic/july-13-2021-kb5004237-os-builds-19041-1110-19042-1110-and-19043-1110-ae798d3c-3de3-4c1f-b9d9-7391b71da889>

**Comment by vladmandic** [comment]
since `human` is designed as a class, you could in theory want to have any number of active instances.
but i don't see any issues with having something like:

```js
let human: Human

const someMethod = () => {
  if (!human) human = new Human();
}
```

also, since JS does not support sub-modules, I prefer to pass `human` instance as parameter to any method thats outside of the main module (and never create an instance inside a submodule).

**Comment by vladmandic** [comment]
btw, i'm closing the issue as resolved, but feel free to ask any questions you might have...
