### ISSUE TITLE
having issue using tenserflow version below 1.6.0

### ISSUE THREAD

**Issue by AshishAvesta** [vladmandic/human#258]
Not bug just a question for help.
I am using the face comparison feature in my electron app.
If I use the TensorFlow version above 1.6.0, which uses **AVX instruction** which may not run on older CPUs.
Can this library work without tfjs-node or we can use the tfjs-node version lower than 1.6.0?

**Environment**
Human library version: 2.4.1
NodeJS and version : 14.17.6
OS : Window10
Electron version : 12.0.18

Below is my configuration for Human.

humanConfig: {
		async: true,
		warmup: 'face',
		backend: 'webgl',
		modelBasePath: process.env.NODE_ENV === 'development' ? modelPath : `${app.getAppPath()}${modelPath}`,
		filter: {
			enabled: true,
			flip: true
		}
       }

Got error while using tfjs-node version: 1.4.0

![image](https://user-images.githubusercontent.com/32563418/159909500-cc379e78-375d-43ac-85a4-25eebd381c63.png)

**Comment by vladmandic** [comment]
Since your intention is to run in a client app, lets eliminate `tfjs-node` completely and not talk about version requirements.  

`Human` can run in browser (for client side deployments) and in node (for server-side deployments). The issue with `ElectronJS` is that its **both**, so depending HOW you load Human, it will detect it runs in node and attempt to use `tfjs-node`. If you load `Human` correctly so that it detects browser instead of node, you should have no issues.

But...I'm not an ElectronJS expert - its been on my list to do a quick how-to for Electron for a while now, just haven't gotten to it just yet. So you'll need to go through Electron's docs to see how that is done for some other libraries?

Now, if there is any issues with platform detection in `Human`, I'd be happy to look at it and if necessary patch it.

**Comment by AshishAvesta** [comment]
Started working on it as you suggest.
Tried to load human as you did in human-next but get an error
![human_error](https://user-images.githubusercontent.com/32563418/160615473-21929c89-608a-4d9b-9a0c-ed520ce0ea00.png)

Did same as you did in RunHuman.tsx

**Comment by vladmandic** [comment]
you can see from the backtrace that electron is still trying to use `nodejs` (**cjs** loader is for node only).  
need to find a way to tell electron not to do that and that import is browser-only.  
but like i said, i don't use electron (it is on my todo list, but havent done it yet).

**Comment by vladmandic** [comment]
any updates?

**Comment by AshishAvesta** [comment]
Sorry, I'm coming into this so late.
I follow your browser example: [](https://github.com/vladmandic/human/tree/main/demo/typescript)
So I just copy human.esm.js to my render code (frontend code that is Reactjs) and load Human from that.

Is this the correct way?

**Comment by vladmandic** [comment]
just created a quick demo app using **human** and **electronjs**, follow that template.
<https://github.com/vladmandic/human-electron>
