### ISSUE TITLE
Why does FPS decrease after using web worker?

### ISSUE THREAD

**Issue by a1782680475** [vladmandic/human#272]
I am sure that the parameter configuration is the same for single thread and multi thread, but the frame rate of web worker is lower than that of single thread.
Your demo results are the same. The frame rate is low under the web worker.

**Comment by vladmandic** [comment]
Overall, running in webworker is expected to be slower than running in main thread - there is no reason why it would be faster if main thread is not doing anything else.

Note that for any work done in webworker, there is an extra step of copying all pixel data to transferrable array on each frame (which is not a small overhead). And higher the input resolution, higher the overhead. Some of the overhead can be minimized by doing input preprocessing on the main thread (using `human.image` method and specifying fixed lower processing resolution like 500px) and sending fixed image in lower resolution to webworker - that way you can get to nearly identical performance - but even then, its *nearly* the same performance - its always a little bit slower.

Advantage of webworker is not overall higher frame rate, but the fact that main thread is not blocked, so if your app needs to do something else, its free to do so and overal, it feels more reponsive (since its never blocked).

I'm closing this as a non-issue, but feel free to post any further questions.
