### ISSUE TITLE
Error: Requested texture size [4739x4739] greater than WebGL maximum on this browser / GPU [4096x4096].

### ISSUE THREAD

**Issue by maxcodefaster** [vladmandic/human#275]
**Issue Description**
HumanGl throws error: Requested texture size [4739x4739] greater than WebGL maximum on this browser / GPU [4096x4096].
<img width="1044" alt="Bildschirmfoto 2022-06-20 um 18 45 38" src="https://user-images.githubusercontent.com/35369883/174647778-62908bda-bf44-46f6-8b60-5e7c77e40472.png">

Models I have activated are face tracking and emotion detection.
2048 or 4096 seems to be reasonable limits. At least as of 2020 it looks like [99% of devices support 4096 but only 50% support > 4096](https://webglstats.com/webgl/parameter/MAX_TEXTURE_SIZE).

**Environment**

Human v2.8
Samsung SM-G991B
Chrome Mobile Webview 102.0.5005
Android 12

**Comment by maxcodefaster** [comment]
Thank you for your work and quick reply.

The error was thrown by a Samsung SM-G991B, Chrome Mobile Webview 102.0.5005 with Android 12. This device seems to have a 4k front camera, so that is where perhaps the error is coming from. 

```ts
new Human({
    modelBasePath: 'tfjs-models',
    warmup: 'face',
    debug: environment.production,
    filter: { enabled: false },
    gesture: { enabled: false },
    face: { mesh: { enabled: false }, iris: { enabled: false }, description: { enabled: false } },
    body: { enabled: false },
    hand: { enabled: false },
  });

private readonly videoConf: MediaStreamConstraints = {
    video: { facingMode: 'user', frameRate: { max: 30 } }, audio: { echoCancellation: false },
  };
```

I disabled `config.filter` because I was worried about performance degradation, but it was probably unnecessary. The workflow we have is: 
Create video stream, and every 500ms run human detection on that stream to get the emotions. (https://bonq.app)

So I see two options: 
1. Just enable `config.filter`
2. Somehow constrain MediaRecorderOptions so that the recorded video is no larger than HD, for example, but still in portrait format. The latter option seemed very difficult last time I tried it, since different devices encode the video information differently and aws media conversion pipeline then does not properly rotate the video.

**Comment by vladmandic** [comment]
Both options are valid:
- `MediaStreamConstraints` is a pain in !@#, but at the end it does work when you twiddle with it. Only issue I have with it is that some constraints are browser-specific, so its not a truly cross-browser solution
- `config.filter` performance is really high, so that should not be a concern. And if you set only `width` or only `height`, it will do the math behind the scenes to keep the same aspect ratio. Only if you set both, then its up to you.

If only thing you're interested is emotion, you might want to experiment with `faceBoxScaleFactor` value in `src/face/blazeface.ts` (i didn't expose it as configurable value, but i probably should) - its basically how tight is crop around the face going to be before passing it to other models such as emotion - and it does have quite an impact.

**Comment by maxcodefaster** [comment]
> 

Wow especially the last part `faceBoxScaleFactor` sounds very interesting ;)  If you could implement a config that would be awesome! Its better than forking. 

I just deleted `config.filter` and will await the results. Do you think it would be wise to set `width` or `height` to lets say a resolution of 480p to further improve performance?

**Comment by vladmandic** [comment]
> Wow especially the last part faceBoxScaleFactor sounds very interesting ;) If you could implement a config that would be awesome! Its better than forking.

i totally forgot, it is exposed in config, but as hidden optional parameter: `config.face.scale`, default value is 1.4  

> Do you think it would be wise to set width or height to lets say a resolution of 480p to further improve performance?

setting low resolution only really improves performance when you're running in web worker as transferring pixel data between threads is not cheap. otherwise, i'd suggest to run with 720p minimum. reason is that after face detection, you still want cropped face box to be ideally 384px (its resized up or down to that resolution). now, if your face takes 90% of frame, then running at 480p is ok. but if face is smaller, then having larger input resolution helps.

btw, i've just noticed that you've disabled face mesh model (because you don't need it). but...face detector is really quick, but resulting boxes are a) not really precise, b) there are some false positives  

face mesh when runs also stabilizes face boxes by removing false positives and rewrite face box coordinates with precise ones. so depending on your use case, you may want to try with mesh enabled even if you don't care about mesh detection

**Comment by maxcodefaster** [comment]
Found the config you are referring to here: https://github.com/vladmandic/human/blob/main/src/face/blazeface.ts#L98

My config with scale factor set to 1.1 and mesh not disabled looks now like this:
```ts
public readonly detection: Human = new Human({
    modelBasePath: 'tfjs-models',
    warmup: 'face',
    debug: false,
    gesture: { enabled: false },
    // @ts-ignore
    face: { iris: { enabled: false }, description: { enabled: false }, scale: 1.1  },
    body: { enabled: false },
    hand: { enabled: false },
  });
  ```

Let's see how those results will perform. Thank you very much! Do you know of any other performance tweaks for my specific usecase?

**Comment by maxcodefaster** [comment]
> > Do you know of any other performance tweaks for my specific usecase?
> 
> Depending how static the input is, you may want to play with caching setting.
> 
> Btw, I'm closing this issue as resolved as original item is no longer a problem - but feel free to post on this thread if you have any further questions.

Ok thank you so far!

To further explain my usecase: I am taking an MediaInput stream from mobile devices front camera and analyze every 500ms the emotions. On low level to medium level devices this causes a lot of performance issues, as we also run video playback and media recorder. So I am thinking on handling the emotion detection on server site. Or do you know of any suitable optimizations to keep human running on the client?

**Comment by vladmandic** [comment]
In that case, I'd go for a web worker implementation - its not faster than running `human` in the main thread (its actually a touch slower as there is extra step or copying pixel data to worker thread which takes couple of ms), but it completely frees up main thread to do anything else without locking up every 500ms when detection runs.

**Comment by ButzYung** [comment]
A bit off topic, but recently I discovered that it's actually faster to pass `ImageBitmap` instead of pixels data as `ArrayBuffer`(`ImageData`) in web worker. The reason is that `ImageBitmap` stays in GPU the whole time, while for `ImageData` it needs to be extracted from the main thread and put it back to GPU in web worker, and these processes take CPU time. The difference can be quite significant, in some cases up to 25% of fps increase. This is tested on `mediapipe` models running on web worker, but I suppose the improvemnet applies to `human` as well.
