### ISSUE TITLE
Not working in Safari WebWorker

### ISSUE THREAD

**Issue by LeoMartinDev** [vladmandic/human#297]
Hi !
I can't manage to make Human work with Safari WebWorker.

Here's `human.env` output:

```
{
   "\\""\"browser\": true,
  \"node\": false,
  \"platform\": \"Macintosh; Intel Mac OS X 10_15_7\",
  \"agent\": \"Mozilla/5.0 AppleWebKit/605.1.15 Version/15.6.1 Safari/605.1.15\",
  \"backends\": [],
  \"initial\": true,
  \"tfjs\": {
    \"version\": \"3.20.0\"
  },
  \"offscreen\": false,
  \"perfadd\": false,
  \"tensorflow\": {},
  \"wasm\": {},
  \"webgl\": {},
  \"webgpu\": {},
  \"cpu\": {
    \"flags\": []
  },
  \"kernels\": []
}"
```

The main error I have is `Error when getting WebGL context: `.
Is this a known issue ? Is there a solution to run Human inside a Safari Webworker ?
Thanks

**Comment by LeoMartinDev** [comment]
I guess it is related to the usage of `OffscreenCanvas` which is not supported by Safari https://caniuse.com/offscreencanvas

**Comment by vladmandic** [comment]
yup, you're right - and `human.env` output shows no offscreen canvas support as well. and since normal canvas is not available in web workers, there is nothing that can be used. i really don't understand apple's safari policy - its been soo far behind in so many areas.

anyhow, not much i can do about it (except add it to known limitations which is my mistake that its not already there)...

**Comment by LeoMartinDev** [comment]
Thanks for the quick reply :)
I guess I'll just run human in the browser instead of inside web worker when OffscreenCanvas is not available in the browser.
Have a nice day
