### ISSUE TITLE
Detect face in device (antspoofing)

### ISSUE THREAD

**Issue by brunogdn** [vladmandic/human#304]
You can use this model to improve antspoofing?

https://universe.roboflow.com/artem-razdyakonov-zgktj/liveness_again/model/8

**Comment by vladmandic** [comment]
that is not **antispoof**, that is **liveness** test - and `human` already has one (see `config.face.liveness`)  

perhaps this one is better, but i cannot say because its not open source (roboflow *says* its a collection of open-source models, but they are hidden behind their api and mandatory key)  

in either case, `liveness` is relatively easy problem to solve, `antispoof` is not (e.g, modern phones use camera augmented with depth-sensing and infra-red sensors which cannot be accessed via api, so i cannot use them)  

anyhow, if you have an actual link to model itself, i'll test it and see how it compares to existing one

**Comment by brunogdn** [comment]
Thank you very much. Your library is very good.

My need is to identify fraud.
I thought of combining liviness and screen detection (cell phones).

Using the current model liveness, the percentage when I'm in front of the camera gets smaller.

What would your suggestion be?

Sorry for English.

**Comment by vladmandic** [comment]
i'll take a look at improving `liveness` and `antispoof`, current model versions are quite old

**Comment by vladmandic** [comment]
i've made some improvements in upcoming v3 of `human`, but its still quite limited.  

since standard cameras do not have depth and ir sensors, best option is to rely on gesture detection so user has to perform a simple gesture before input is accepted.  

for example, take a look at `demo/faceid` 

other than that, i really don't want to go too deep in this area since its always going to be behind commercial ones due to lack of ir and depth sensor data.
