### ISSUE TITLE
WebWorker not working

### ISSUE THREAD

**Issue by djthegr8** [vladmandic/human#32]
**Issue Description**
Worker not working, showing `creating worker thread` and then not progressing
**Steps to Reproduce**
Just set `useWorker` to true
**Expected Behavior**
Works as expected
**Environment**
- Browser or NodeJS and version (e.g. NodeJS 14.15 or Chrome 86) Chrome
- OS and Hardware platform (e.g. Windows 10, Ubuntu Linux on x64, Android 10) Win7-x64
- Packager (if any) (e.g, webpack, rollup, parcel, esbuild, etc.)

**Additional**
- For installation or startup issues include your `package.json`
- For usage issues, it is recommended to post your code as [gist](https://gist.github.com/)

**Comment by vladmandic** [comment]
On **Chrome**, only issue I could find was load/warmup on startup which was on main thread regardless is web worker is enabled or not. now load/warmup is skipped if web worker is enabled.

Another web-worker issue is that it doesn't pass some real-time config changes to worker, so web-worker will use settings as they were during startup (e.g., can't change backend once web-worker has been initialized).  
This is solvable, but a low priority for now.  

Please check if it is working now in Chrome - I cannot reproduce any other issues.

On **Firefox**, there is tons of issues!

Firefox specific issues:
- doesn't support `WebGL` in web worker, usage limited to WASM  
- due to WebGL memory handling, it's *half the performance* of Chrome when using WebGL  
  (or any browser using Chromium)  
- doesn't support import modules in web worker, must compile worker.js  
  but since human is already compiled in demo app, this means demo + worker would be *double the size* just because of Firefox  

But here biggest one is:
- doesn't support `OffscreenCanvas`, must fallback to DOM  
- since `DOM` doesn't exist by definition in web worker  
  can't use image pre-processing in web worker at all  

I could bypass image pre-processing, but there simply isn't a good way to fetch screen buffer in Firefox when inside web worker.  

**All-in-all, this is a huge pain and until Firefox supports OffscreenCanvas, I will not support Firefox in web worker.**  
(They've actually implemented OffscreenCanvas over a year ago, but still have not included in in official distribution)

In general, I know web workers are the latest fashion since you can do processing in worker thread without blocking main thread. But passing messages between main thread and worker thread adds 20ms latency on each message, so you're loosing quite a bit of performance when running a live video. 

I'd rather live with slight blocking on UI thread than drop performance by several frames. Workers would make sense if performance was soo low to start with and main UI was relying on interpolation of very slow results - definitely valid use case, but that is outside of `demo` scope. If someone wants to create an app like that using `Human` library, please go ahead, but that is not in the scope of library.

**Comment by djthegr8** [comment]
👍
