### ISSUE TITLE
Would tensorflow/tfjs-node-gpu be something that would add value to this project?

### ISSUE THREAD

**Issue by delebash** [vladmandic/human#35]
TensorFlow js node_gpu seems like it could further improve performance.  Just thought you might be interested see https://www.tensorflow.org/js/guide/nodejs

**Comment by vladmandic** [comment]
i already support `tfjs-node` and `tfjs-node-gpu`, but cannot do much with it since face model uses `forwardFunc()` operation that are not yet implemented in them. body and hand models work fine.

see `demo/node.js` for trivial example.

fyi, `forwardFunc()` is critical to calculate face rotation and feed result to next layer, it's the key why face model is as efficient and precise as it is. and why it's so much better than for example, hand model where rotation is done in really bad way.

issue is pending on tfjs side (i'm already talking to devs), once `forwardFunc()` is implemented in `tfjs-node` and `tfjs-node-gpu`, i'll do more testing and write an extensive demo.

closing this issue.
