### ISSUE TITLE
Give error on 1 device with interesting settings

### ISSUE THREAD

**Issue by shurshilov** [vladmandic/human#350]
give thist error
![WhatsApp Image 2023-03-27 at 17 43 59](https://user-images.githubusercontent.com/11828278/227975023-fdb09599-5ef5-42f3-bcc0-fe21efb28ccb.jpeg)

when we disable angel webgl not work
when we enable angel webgl starts working immediately
check on this site 
https://browserleaks.com/webgl#howto-detect-webgl
![WhatsApp Image 2023-03-27 at 17 05 18](https://user-images.githubusercontent.com/11828278/227963652-0b3a0d28-81e2-4c64-a114-e11adde493f2.jpeg)
![WhatsApp Image 2023-03-27 at 17 05 18 (1)](https://user-images.githubusercontent.com/11828278/227963663-4dad8ad7-8182-4fad-9f4d-532262208b25.jpeg)
![WhatsApp Image 2023-03-27 at 17 05 19](https://user-images.githubusercontent.com/11828278/227963675-d7332624-fbbe-49ec-92de-3fc9d7daba83.jpeg)

**On the last 3 screenshots, the working version. If angel webgl False there will be an error like in the first screenshot**

**Comment by vladmandic** [comment]
Key error is

> Failed to link vertex and fragment shaders

That is a very generic OpenGL error (OpenGL error handling is a nightmare), but most commonly it happens when there is insufficient VRAM to perform operation.

To confirm that, can you try running `human` with modified configuration and disable most of the models, leave just one (for example face detect) as enabled. And then try enabling others one by one.

And you can navigate to <chrome://gpu> and monitor gpu log messages at the bottom.

Having said that, Intel HD 5500 is a veeery old GPU, from 2014.  

And **Angle** (not *angel*) is Google's very performant but not very efficient way to execute OpenGL calls on GPU.
When you switch backend to D3D, it uses compatibility mode which is not as fast, but more efficient, especially when it comes to memory allocation.  

Also, given the age of that card, I doubt any real hardware acceleration is helping - you may want to try out using `wasm` backend instead of `webgl` so execution happens on CPU instead of GPU.

**Comment by shurshilov** [comment]
YEs WASM work for this client) so which config will good for this as minimal?but with face recognition and detect enabled?
I use
            const myConfig = {
                debug: false,
                async: true,
                modelBasePath: '/hr_attendance_face_recognition_pro/static/src/js/models',
                face: { // runs all face models
                    face: { enabled: true },
                    mesh: { enabled: true},
                    description: { enabled: true },

                    detector: { rotation: false },
                    iris: { enabled: false },
                    emotion: { enabled: false },
                },
                hand: { enabled: false },
                body: { enabled: false },
                object: { enabled: false },
                gesture: { enabled: false },
                segmentation: { enabled: false },
                filter: { enabled: false },
            };
            for this client also wasw off cause

**Comment by shurshilov** [comment]
Thank you!
