### ISSUE TITLE
Stop at initializing... after loading the website

### ISSUE THREAD

**Issue by trofa9923** [vladmandic/human#365]
![image](https://github.com/vladmandic/human/assets/73928922/2d347c28-255c-4ab5-9270-a69ddf6fac2d)

this is the screenshot of my logs in my browser. 

can you help me?

**Comment by vladmandic** [comment]
- is this happening when you're using default demo link?
- what is your platform and browser? by default, as far as i know, no browser has `webgpu` enabled unless you manually enabled it in browser's advanced options
- can you try <https://vladmandic.github.io/human/demo/index.html?backend=webgl> ?
  this will use same demo, but force backend to standard webgl instead of webgpu
- can you try <https://vladmandic.github.io/human/demo/typescript/index.html> ?  
  this will use slightly different demo

**Comment by vladmandic** [comment]
closing as no updates.
