### ISSUE TITLE
modularize loading of iris and mesh models

### ISSUE THREAD

**Issue by Jimmysh** [vladmandic/human#37]
**Issue Description**
iris.bin is still loaded when iris is set to false.
**Steps to Reproduce**

set config
```
 iris:{
    enabled:false,
...}
```
**Expected Behavior**
iris.bin file not loaded

**Environment
Chrome 86, node 14, Mac OS 10 
dynamic create script element to load human.
```js
document.createElement('script')
```

**Comment by vladmandic** [comment]
good catch.

face.detector, face.mesh and face.iris are a special case since they work in a single pipeline, they are all loaded together if detector is enabled.
but if face.mesh or face.iris have `enabled: false`, their execution will be skipped in runtime.

is this a problem? model sizes are really small, (iris is 2.5MB), so it shouldn't hurt load performance.

**Comment by vladmandic** [comment]
btw, its not related to the question, but why are you doing this? 
`document.createElement('script')`

**Comment by Jimmysh** [comment]
> btw, its not related to the question, but why are you doing this?
> `document.createElement('script')`

I want to lazy load `human`. But this project still in angular 6.  no ` import('xxx.js')` function.  

The models is very big for me. can we have a smaller version to fit mobile. Some places don't have fast internet and they don't have the patience to wait.

**Comment by vladmandic** [comment]
Regarding network saving, did you look at serving app and models with **brotli** or **gzip** support?  
That's what `server/dev/js` does internally as well and saving is quite significant.

And for any subsequent loads, I normally prefer to cache everything client side in *local storage* using *service worker*.  
That's not implemented in this demo, but you can take a look at <https://github.com/vladmandic/pigallery/blob/master/client/index/pwa-serviceworker.js> and <https://github.com/vladmandic/pigallery/blob/master/client/index/pwa-register.js> for example.

That way, load is only slow first time user loads the app and it's nearly instant later.

But yes, I can modularize `iris` and `mesh` models as well.

**Comment by vladmandic** [comment]
I've modularized **face iris & mesh** and **hand skeleton** models.  

The side-effect is that they cannot be dynamically disabled/enabled like all other models once first load has completed, you need to manually unload the model so the pipeline can be reinitialized.

For example, if `config.face.iris.enabled = false`, iris model will not be loaded.  
But to enable it in runtime, you need to *reset* the face pipeline since models that are part of the pipeline cannot be easily added to existing pipeline:
```js
  myConfig.face.iris.enabled = false // start with iris model disabled
  await human.load(myConfig)
  const res = await human.detect(input, myConfig)

  human.models.facemesh = null // this unloads face pipeline
  myConfig.face.iris.enabled = true // enable iris model
  await human.load(myConfig)
  const res = await human.detect(input, myConfig)
```

Implemented via <https://github.com/vladmandic/human/commit/c688254269846aaf8f21af6c843bedc04c2d07d3>

Please verify before issue can be closed.

**Comment by vladmandic** [comment]
closing as resolved.

**Comment by Jimmysh** [comment]
Thanks

**Comment by Utopiah** [comment]
`iris: { enabled: false },` still results in `log: ["14:40:08.328","Human:","load model:","./human/models/iris.json"]` which as described can be problematic for mobile pages.

**Comment by vladmandic** [comment]
@Utopiah, I don't see your entire configuration, but it's `face.iris.enabled`, not just `iris.enabled`

I just tried with 
```js
  face: { enabled: true,
    detector: { return: true },
    mesh: { enabled: true },
    iris: { enabled: false },
    description: { enabled: false },
    emotion: { enabled: false },
  },
```

And messages are correct:
```log
09:07:00.679 Human: load model: ../models/blazeface.json
09:07:00.750 Human: load model: ../models/facemesh.json
09:07:00.750 Human: tf engine state: 3501876 bytes 231 tensors
```

**Comment by Utopiah** [comment]
Currently using 
```javascript
const config = { 
        backend: 'webgl',
        modelBasePath: './human/models/',
        gesture: { enabled: false },
        body: { enabled: false },
        hand: { enabled: false },
        iris: { enabled: false }, // still loaded but only 2.5Mb
        profile: { enabled: false },
};
```

but if I add ` face: { iris: { enabled: false } } ` I get indeed what I expected.

I now see my mistake, looking at the full configuration I didn't see that iris was part of face. Thanks for the clarification.
