### ISSUE TITLE
wasm performance issues

### ISSUE THREAD

**Issue by djthegr8** [vladmandic/human#40]
**Issue Description**
i am getting very low fps for WASM in my hand-tracking, so just one model that too without landmarks. This would give me 3FPS with WASM SIMD Threaded, which is very very less
**Steps to Reproduce**
Simply check my [demo](https://humandemotest.github.io)
**Expected Behavior**
10FPS, at least?

The source code is [here](https://github.com/humandemotest/humandemotest.github.io/demo/index.html)

**Comment by vladmandic** [comment]
when filing a performance issue, try to provide as much data as possible:
- what hardware?
- which browser?
- what is the resolution? WASM is very sensitive to input resolution
- what is the `webgl` performance for the same configuration? Need to know how much slower is `wasm`, not just *it's slow*

anyhow, i did some digging and seems there is a quite a bug in `wasm` backend which causes this model to loose hand tracking so it has to be redone almost every frame - so all the caching optimizations are not used. this needs to be fixed in tfjs.

see <https://github.com/tensorflow/tfjs/issues/4311> for details.

**Comment by djthegr8** [comment]
Hardware (as Wasm is on CPU) i3-3rd
Chrome latest
Resolution don't remember, can you check in the demo link I sent?
WebGL didn't check... However the general demo is 6fps just hands but
landmarks itself is 3fps making no sense to me....

**Comment by vladmandic** [comment]
chrome *latest* - can you be precise?
there are prod, beta, dev and canary channels and i cannot guess which one you use. and i don't know if your chrome was updated immediately or not (e.g., chrome 87 came out few days ago and had several breaking changes).

resolution - no, it should be reported in the issue.
plus the link you sent is just a link to readme and inside it link to demo goes back to my page. so i don't know where your demo is.

webgl - anytime there is a performance issue, there should be something to compare it with. reference model, different backend, etc. just saying "it's slow" doesn't help me to investigate.

anyhow, seems there is a bug in wasm backend as i wrote before, i'll wait for a feedback from tfjs team.

**Comment by djthegr8** [comment]
I really don't think it's the browser, but if you really want it, it's
Chrome 86 Production...
Also, yes that was an incorrect link,
humandemotest.github.io/demo/index.html is the right one... The input res
is 256, camera and display is 300x150

**Comment by vladmandic** [comment]
i checked your demo and execution on my notebook with i7-8750 is 9+ fps, that is well within expectations.
looking at stats, image processing is ~10ms and model inference is ~100ms, so on my system resolution could be 4x and it would only drop to 8fps.

i'm afraid that until there is more optimized wasm backend published by tfjs team, there is nothing i can do here.
