### ISSUE TITLE
Facing “Reference Error: tJ is not defined” error when trying to precompile using "npm run build" command.

### ISSUE THREAD

**Issue by viwinATag** [vladmandic/human#437]
**Issue Description**
I am facing this error when i am trying to precompile using the npm run build command, “Reference Error: tJ is not defined” and not capturing any inferences, and if i am disabling wasm (--js-flags=--noexpose_wasm), then the application is working well and capturing all the inferences. Possible solutions for fixing this?

**Environment**
Application details: Frontend- NextJS, Backend- Django
Human version: 3.2.1
Backend: wasm
Typescript version: 5.3.2
platform: "X11; Ubuntu; Linux x86_64; rv:123.0"
agent: "Mozilla/5.0 Gecko/20100101 Firefox/123.0"
Tfjs: version: "4.17.0"
Wasm path: https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-backend-wasm@4.17.0/dist/
I am also adding the entire logs in the file for reference.
[no_inferences.txt](https://github.com/vladmandic/human/files/14830344/no_inferences.txt)

Logs after precompilation using “npm run build” command:
![Screenshot from 2024-04-01 17-45-27](https://github.com/vladmandic/human/assets/163999401/07c463bb-81cf-4761-90bf-7a310fb3b382)

**Comment by vladmandic** [comment]
what do you mean by "precompile"? if its just running `npm run build` for human, then what is the output of that? any warnings/errors?

also, the errors message from browser console is not informative at all since your "compile" minified the code. if you want to troubleshoot, run without minification so actual error can be seen as it happens.
