### ISSUE TITLE
Facemesh, Handpose, and normalized mesh

### ISSUE THREAD

**Issue by ButzYung** [vladmandic/human#49]
**Issue Description**

The `Human` version of Facemesh returns only the normalized mesh data, unlike the `TFJS` version which returns both `.scaledMesh` (normalized, equvialent to the `Human` version of mesh) and `.mesh`, the raw 3D coordinates which is what I need for 3D calculations. Please consider returning both version of mesh in future version of  `Human`.

A similar issue occurs for Handpose. Both `Human` and `TFJS` version of Handpose return only the normalized mesh data. In the case of `TFJS`, I use a trick and modify Handpose by returning a normalized z value as well (i.e. the 3D aspect ratio is more accurate when all xyz are normalized instead of just xy), something like the following (not sure if this is the right way to get a normalized z though).

https://github.com/vladmandic/human/blob/main/src/hand/handpipeline.js

```
    return coordsRotated.map((coord) => [
      coord[0] + originalBoxCenter[0],
      coord[1] + originalBoxCenter[1],
      coord[2] * scaleFactor[0], // normalized it by multiplying with the same x scaleFactor
    ]);
```

I wonder if something can be done for the `Human` version of Handpose.

**Comment by vladmandic** [comment]
`Human` returns coordinates in the same range as input image. Some call that *scaled*, but that is bad.  

Normalized typically refers to coordinates that are modified to fit specific range. So if you want coordinates in format of 0..1, that would be *normalized*.  

I've removed normalized coordinates from output as my primary goal was to keep response object size to minimum so if I choose to store it in DB or something like that, I don't have to filter out extra values. For the same reason, I even truncate some float values on output (e.g, who needs score on 10 decimal points?).  

Anyone that needs normalized values is not just drawing a 2D image on the screen (you're a good example) and I assume they can do a trivial oneliner using `map()` on each coordinate set and dividing by input size. I could be convinced otherwise if there is more demand.  

Regarding Z axis, I though about it and I left it as-is simply because there I didn't think of a meaningful way to determine scale factor at the time. I'm open to suggestions. For now, I've set it to average of X and Y scale (changed).

**Comment by ButzYung** [comment]
> Anyone that needs normalized values is not just drawing a 2D image on the screen (you're a good example) and I assume they can do a trivial oneliner using `map()` on each coordinate set and dividing by input size. I could be convinced otherwise if there is more demand.

In the case of Facemesh, judging from the source codes, to covert the returned mesh (`coordsRotated`) back to the raw scale, one would need at least the `scaleFactor` from the `transformRawCoords`. This doesn't seem possible using just the returned results. I understand that returning another mesh data with the rawcoords may be overkill (since it is not needed by many use cases). Perhaps conditionally returning it via config?

**Comment by vladmandic** [comment]
can i interest you in contributing to the project? pull requests would be welcome :)

**Comment by ButzYung** [comment]
> 
> 
> can i interest you in contributing to the project? pull requests would be welcome :)

Done. Hope you don't mind something from a AI/Tensorflow noob lol

**Comment by vladmandic** [comment]
contributions as welcome! i'll review it today or latest tomorrow.

**Comment by vladmandic** [comment]
pull request merged. care to do the same for other models (e.g. hand, etc.)? :)

**Comment by vladmandic** [comment]
i'm closing this issue, but feel free to open a new one (or better yet, create a pull request) for remaining models.
