### ISSUE TITLE
load swallows errors

### ISSUE THREAD

**Issue by pgg** [vladmandic/human#495]
**Issue Description**
```human.load();``` call errors are swallowed

**Steps to Reproduce**
```https://stackblitz.com/edit/vitejs-vite-ahmqmo?file=app.js```

**Comment by vladmandic** [comment]
i appreciate simple reproduction, but please be a bit a bit more descriptive in the issue itself.
and this is a design decision, errors are logged but not thrown - because desired behavior is to continue working even if user does not have error handling and why break everything if a single model is not working.

if you want to explicitly throw, you can modity this line: https://github.com/vladmandic/human/blob/df73c8247f652acca276a3ecad8c96031cf869cd/src/tfjs/load.ts#L81
to add `throw err` after log statement.

of submit a feature request (or even better, a pr) where throw becomes a configurable item.

**Comment by pgg** [comment]
in your current design, how do we know / test if a model has failed after loading / warming ?

**Comment by vladmandic** [comment]
i've added `loaded` property to each model in stats, also numloaded and sizeloaded are now correct and as a consequence, percentageloaded math is also correct.
![image](https://github.com/user-attachments/assets/7a4ba52e-84b6-4775-9fa0-e4ff3739ef98)

new version will be published shortly.

**Comment by pgg** [comment]
can confirm this works now in both pre cached and post cached, thanks!
