### ISSUE TITLE
Faceres Original Model

### ISSUE THREAD

**Issue by ceyxasm** [vladmandic/human#503]
Hello @vladmandic 
You have given credits to [HSE_FaceRes_tf](https://github.com/av-savchenko/HSE_FaceRec_tf/tree/master) for face description models. Moreover, you provide two models for face description calculation.
One is faceres and other is faceres-deep. I have a few queries
1. What is the difference between the two models: `faceres` and `faceres-deep`?
2. Which one of the two corresponds to the original model provided by HSE_FaceRes_tf
3. I generated embeddings using all the three models; 2 using human and 1 from HSE_FaceRes_tf; but no two match. Is this expected? Or am I missing some image preprocessing?

Motivation: I want to run a model in my python backend to store the embeddings of images of people. When same people are captured by human; I am using descriptors given by human to do a recognition test.

To generate human embeddings I used your code and to generate embeddings from HSE_FaceRes_tf, I used their code @ [here](https://github.com/av-savchenko/HSE_FaceRec_tf/blob/master/facerec_test.py).
I also ran their code with ImageNet normalizations and RGB->BGR but nothing worked.

**Comment by ceyxasm** [comment]
Adding further to this; the way currently the model calculates scores is not super discriminative. 
![image](https://github.com/user-attachments/assets/d33b879f-f8f5-437f-80cf-0b1dcee1ae8a)
Is calculating euclidean distance between the embeddings to calculate the score the best method here??

**Comment by vladmandic** [comment]
if you're using python backend and want to compare embeddings generated by human with ones from python, its never going to be identical. and yes, human does do preprocessing of images - you can always tell human to return actual face as well (not just results) so you can see what is embedding being generated on. you could even then process that face in python if you wish.

also, human supports eucliean distance as well as other methods - its configurable and i believe documented.
e.g. you may have better score discrimination using 3rd order instead of 2nd order.
