### ISSUE TITLE
Can I know if a person is looking at the camera ?

### ISSUE THREAD

**Issue by simon-lanf** [vladmandic/human#57]
I know that right now I can know if the user's eyes are facing the camera by knowing they are both at the same distance from the camera. The problem is that if someone is in the far left for example, this person would have to turn it's head in an angle from the camera's point of view and now this person is not facing the camera.

I wonder if there is a way to detect these cases. We could triangulate where the person is looking from the 3d coordinates, or try to guess if the person is looking by adding parameters X and Z in the equation, for example if you are in the far left, you should be facing slightly the right.

Let me know if you have any idea.

edit: I'd like to add that I'm not looking for exact gaze or where the iris points. just if the head if turned to the camera.

**Comment by vladmandic** [comment]
one way that comes to mind is to compare the size of the iris for left and right eye - if a person is looking towards camera, they should be within small margin. and that should hold regardless if person is in the center of the frame or at the edge and looking at an angle.

in `demo/draw.js` you have:
```js
          const sizeX = Math.abs(face.annotations.leftEyeIris[3][0] - face.annotations.leftEyeIris[1][0]) / 2;
          const sizeY = Math.abs(face.annotations.leftEyeIris[4][1] - face.annotations.leftEyeIris[2][1]) / 2;
```
and
```js
          const sizeX = Math.abs(face.annotations.rightEyeIris[3][0] - face.annotations.rightEyeIris[1][0]) / 2;
          const sizeY = Math.abs(face.annotations.rightEyeIris[4][1] - face.annotations.rightEyeIris[2][1]) / 2;
```
but...iris is a small object, so it could be unreliable in borderline cases where face is small or iris size cannot be detected accurately.

another way would be to look at z-axis of points on left and right edge of the face.  
like it's currently done in `src/gesture/gesture.js`:
```js
      const eyeFacing = res[i].mesh[35][2] - res[i].mesh[263][2];
      if (Math.abs(eyeFacing) < 10) gestures.push({ face: i, gesture: 'facing camera' });
      else gestures.push({ face: i, gesture: `facing ${eyeFacing < 0 ? 'right' : 'left'}` });
```
but instead of currently fixed 10% threshold, project both points on a semi-circle with radius being distance from the camera and adjust z value before calculating difference. and use iris-based calculation for distance (included in the default result set) to calculate radius of the semi-circle .  

it's a bit more approximations, but since points are much more spread out i'd guest it could end up being more reliable.

**Comment by vladmandic** [comment]
i've added gesture detection for iris-based `looking at camera` and published a new version, so i'm closing this issue.
