### ISSUE TITLE
Firefox webgl and performance

### ISSUE THREAD

**Issue by ost12666** [vladmandic/human#59]
I am getting this error on firefox with my project:

Error when getting WebGL context:  Error: Cannot create a canvas in this context 2 bundle.worker.js:40131:13
Initialization of backend webgl failed bundle.worker.js:53628:15
MathBackendWebGL@http://localhost:3000/static/js/bundle.worker.js:15334:13
../audio-ml-plugin/node_modules/@tensorflow/tfjs-backend-webgl/dist/base.js/<@http://localhost:3000/static/js/bundle.worker.js:16354:96

In the human demo Firefox is half the FPS of Chrome.

Any ideas?

Thanks

**Comment by ButzYung** [comment]
Web worker version of `human` probably doesn't work on Firefox because `OffscreenCanvas` is required, which is still a behind-a-flag feature on Firefox.

**Comment by vladmandic** [comment]
First, `http://localhost:3000/static/js/bundle.worker.js:15334:13` is clearly your custom bundle - so I cannot correlate it to an actual source code. Please post actual error backtrace and I'll take a look.

But, if you're using web workers, **Human** currently does not support Firefox due to lack of `OffscreenCanvas()` support so there is no efficient way to handle image data inside a worker thread. It could be done with some workaround, but it would be much slower and I'd rather not do special-case just for Firefox - they should really enable the feature.  
(@ButzYung you're correct & thanks for jumping in)

Second, regarding Firefox performance using `webgl` backend, yes, it is slower primarily because Firefox performs very aggressive GPU memory garbage collection so uploaded GL shaders do not stay cached and need to be re-uploaded frequently. Unfortunately, there is no way to modify this Firefox behavior.  
But in my test cases, difference is ~20% and not 50%. Can you provide more details on this?

**Comment by ost12666** [comment]
I am actually not using Web Worker but the strange thing is that I always get this error but it still works...

BTW you were right, it works well with the UI and all without Web Worker. On your demo I see on my Mac 14 fps for Chrome and 7 fps for Firefox.

Anyway I am trying to run some instances on remote browsers controlled by Microsoft Remote Desktop and on Machine without GPU card Chrome failed to use WebGL and nothing works while Firefox works on the same machine. On another machine with a GPU card Chrome works and even get a performance boost (compared to my Mac). but Firefox does not get the same boost.

Anyway I am generally very happy with the library.

**Comment by vladmandic** [comment]
> the strange thing is that I always get this error but it still works...

Like I said, I need an actual backtrace to investigate.  
One possibility is that registration of WebGL2 plus extensions in `src/tfjs/backend.js` goes wrong which is a non-fatal error since basic WebGL1 is still operational.

Also, could you copy&paste browser console message regarding GL version and TF flags when using Chrome and Firefox?
It should look like 
```
11:35:22.243 Human: gl version:WebGL 2.0 (OpenGL ES 3.0 Chromium) renderer:WebKit WebGL
11:35:22.243 Human: tf flags: ...
```

> on my Mac 14 fps for Chrome and 7 fps for Firefox.

This is just a general note - MacOS is fairly closed platform, any hardware integration is really difficult. Chrome uses Blink which is a fork of Apple's version of WebKit so it's likely much closer to hardware optimizations. Firefox on the other hand uses variations of Gecko engine which doesn't have same level of Mac integration.

**Comment by ost12666** [comment]
Chomre:

11:58:36.696 Human: version: 0.9.24 TensorFlow/JS version: 2.8.2
0.chunk.js:287641 11:58:36.696 Human: setting backend: webgl

0.chunk.js:287641 11:58:36.720 Human: gl version:WebGL 2.0 (OpenGL ES 3.0 Chromium) renderer:WebKit WebGL

0.chunk.js:287641 11:58:36.720 Human: tf flags: ObjectDEBUG: falseHAS_WEBGL: trueIS_BROWSER: trueIS_NODE: falseIS_TEST: falsePROD: trueTENSORLIKE_CHECK_SHAPE_CONSISTENCY: falseWEBGL_BUFFER_SUPPORTED: trueWEBGL_CHECK_NUMERICAL_PROBLEMS: falseWEBGL_CONV_IM2COL: trueWEBGL_CPU_FORWARD: trueWEBGL_DELETE_TEXTURE_THRESHOLD: -1WEBGL_DOWNLOAD_FLOAT_ENABLED: trueWEBGL_FENCE_API_ENABLED: trueWEBGL_FORCE_F16_TEXTURES: trueWEBGL_LAZILY_UNPACK: trueWEBGL_MAX_TEXTURES_IN_SHADER: 16WEBGL_MAX_TEXTURE_SIZE: 16384WEBGL_PACK: trueWEBGL_PACK_ARRAY_OPERATIONS: trueWEBGL_PACK_BINARY_OPERATIONS: trueWEBGL_PACK_DEPTHWISECONV: trueWEBGL_PACK_IMAGE_OPERATIONS: trueWEBGL_PACK_UNARY_OPERATIONS: trueWEBGL_RENDER_FLOAT32_ENABLED: falseWEBGL_SIZE_UPLOAD_UNIFORM: 0WEBGL_VERSION: 2__proto__: Object

**Comment by ost12666** [comment]
Firefox:

12:02:56.115 Human: version: 0.9.24 TensorFlow/JS version: 2.8.2 log.js:6
12:02:56.115 Human: setting backend: webgl log.js:6

12:02:56.146 Human: gl version:WebGL 2.0 renderer:Mozilla

12:02:56.147 Human: tf flags: 

DEBUG: false
​
HAS_WEBGL: true
​
IS_BROWSER: true
​
IS_NODE: false
​
IS_TEST: false
​
PROD: true
​
TENSORLIKE_CHECK_SHAPE_CONSISTENCY: false
​
WEBGL_BUFFER_SUPPORTED: true
​
WEBGL_CHECK_NUMERICAL_PROBLEMS: false
​
WEBGL_CONV_IM2COL: true
​
WEBGL_CPU_FORWARD: true
​
WEBGL_DELETE_TEXTURE_THRESHOLD: -1
​
WEBGL_DOWNLOAD_FLOAT_ENABLED: true
​
WEBGL_FENCE_API_ENABLED: true
​
WEBGL_FORCE_F16_TEXTURES: true
​
WEBGL_LAZILY_UNPACK: true
​
WEBGL_MAX_TEXTURES_IN_SHADER: 16
​
WEBGL_MAX_TEXTURE_SIZE: 8192
​
WEBGL_PACK: true
​
WEBGL_PACK_ARRAY_OPERATIONS: true
​
WEBGL_PACK_BINARY_OPERATIONS: true
​
WEBGL_PACK_DEPTHWISECONV: true
​
WEBGL_PACK_IMAGE_OPERATIONS: true
​
WEBGL_PACK_UNARY_OPERATIONS: true
​
WEBGL_RENDER_FLOAT32_ENABLED: false
​
WEBGL_SIZE_UPLOAD_UNIFORM: 0
​
WEBGL_VERSION: 2

**Comment by vladmandic** [comment]
unfortunately, there is nothing strange in the flags.  

and you didn't post full backtrace of error `Error when getting WebGL context: Error: Cannot create a canvas in this context`, only first two lines.
but i did notice one thing - backtrace is from `tfjs-backend-webgl` which is a module dependency of `audio-ml-plugin`.  
how are you using `Human`, is it bundled version or non-bundled? if it's bundled, you most likely have two versions of tfjs and not sure if they match.  

anyhow, i just pushed new version of **Human**, can you try setting backend to my custom version of webgl backend which has extra diagnostics in `src/tfjs/backend.js`?  
(also updated tfjs to 2.8.3)  

for example:
```js
const userConfig = { backend: 'humangl' };
```

the log produced should look like:
```log
09:25:55.719 Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36 Edg/87.0.664.75
09:25:55.743 Human: version: 0.9.24 TensorFlow/JS version: 2.8.3
09:25:55.744 Human: setting backend: humangl
09:25:55.744 Human: backend registration: humangl
09:25:55.771 Human: backend registered: humangl
```

**Comment by ost12666** [comment]
We have audio stuff that uses tfjs so I use the non bundled version and making everything is using the same tfjs version. I will try to do what you propose later. Will humangl have the same performance as webgl? What is the difference or should I use it only for the logs?

**Comment by vladmandic** [comment]
right now, `humangl` backend uses custom canvas to register backend, but actual operations are taken from `webgl` backend.  

reason for having it is so I can have custom GL hooks into canvas and monitor & profile GL operations as they are executed which I can't if I can't reach canvas that is internally used by default `webgl` backend. If profiling is disabled (which it is by default), there is no functional difference between `humangl` and `webgl`.

**Comment by ost12666** [comment]
Cool I will use it. Do you want me to turn on profiling for debugging this thing?

**Comment by vladmandic** [comment]
No, profiling will slow down your code 20x and not likely to show anything. It's useful for me when I'm optimizing models so I can see which operations are taking the most time.

**Comment by ost12666** [comment]
Firefox (didn't see any new info):

18:00:41.015 Human: version: 0.9.24 TensorFlow/JS version: 2.8.2 log.js:6
18:00:41.015 Human: setting backend: humangl log.js:6
18:00:41.015 Human: registering humangl backend

Error when getting WebGL context:  Error: Cannot create a canvas in this context 2 bundle.worker.js:40131:13
Initialization of backend webgl failed

MathBackendWebGL@http://localhost:3000/static/js/bundle.worker.js:15334:13
../audio-ml-plugin/node_modules/@tensorflow/tfjs-backend-webgl/dist/base.js/<@http://localhost:3000/static/js/bundle.worker.js:16354:96
initializeBackend@http://localhost:3000/static/js/bundle.worker.js:53586:44
initializeBackendsAndReturnBest@http://localhost:3000/static/js/bundle.worker.js:53682:16
get backend@http://localhost:3000/static/js/bundle.worker.js:53468:16
makeTensor@http://localhost:3000/static/js/bundle.worker.js:54059:5
zeros@http://localhost:3000/static/js/bundle.worker.js:89121:57
apply@http://localhost:3000/static/js/bundle.worker.js:116124:79
addWeight@http://localhost:3000/static/js/bundle.worker.js:109865:35
build@http://localhost:3000/static/js/bundle.worker.js:117423:24
apply/<@http://localhost:3000/static/js/bundle.worker.js:109586:14
nameScope@http://localhost:3000/static/js/bundle.worker.js:106537:17
apply@http://localhost:3000/static/js/bundle.worker.js:109571:69
add@http://localhost:3000/static/js/bundle.worker.js:125157:15
fromConfig@http://localhost:3000/static/js/bundle.worker.js:125693:13
deserializeKerasObject@http://localhost:3000/static/js/bundle.worker.js:126493:35
deserialize@http://localhost:3000/static/js/bundle.worker.js:123560:93
loadLayersModelFromIOHandler@http://localhost:3000/static/js/bundle.worker.js:124991:90

**Comment by vladmandic** [comment]
I guess you're using **Human** from NPM? I pushed update on Git, but didn't update actual NPM so this output is without diagnostics. I just uploaded new NPM, version 0.9.25.

**Comment by ost12666** [comment]
Thanks, I am afraid I wasted your time, the error comes even if I disable the human related code in the app and leave only the audio stuff, so its probably comes from there. Somehow when I see webgl I always thing about visual and forget it is used as a backend :) Do you still need me to run with the new version?

**Comment by vladmandic** [comment]
No worries.

And yes, it should still help to pinpoint the issue, even if it's not in **Human***.

**Comment by ost12666** [comment]
Ok thanks

18:30:45.279 Human: version: 0.9.25 TensorFlow/JS version: 2.8.3 log.js:6
18:30:45.280 Human: setting backend: humangl log.js:6
18:30:45.281 Human: backend registration: humangl log.js:6
18:30:45.291 Human: backend registered: humangl

I don't see any new information. Anyway I always get (and got in the past) those warnings in the beginning (this is only a part of the list). Maybe some tfjs conflict?

Platform browser has already been set. Overwriting the platform with [object Object]. environment.ts:57
cpu backend was already registered. Reusing existing backend factory. engine.ts:238
The kernel '_FusedMatMul' for backend 'cpu' is already registered kernel_registry.ts:142
The kernel 'Abs' for backend 'cpu' is already registered kernel_registry.ts:142
The kernel 'Acos' for backend 'cpu' is already registered kernel_registry.ts:142
The kernel 'Acosh' for backend 'cpu' is already registered kernel_registry.ts:142
The kernel 'Add' for backend 'cpu' is already registered kernel_registry.ts:142
The kernel 'AddN' for backend 'cpu' is already registered kernel_registry.ts:142

**Comment by vladmandic** [comment]
it doesn't pinpoint the problem exactly, but does provide some info.

first of all, there are no errors between: `Human: backend registration: humangl` and `Human: backend registered: humangl`. which performs all canvas creation and registration operations like `webgl` normally would - it all works just fine on the main thread.

actual warnings about `already registered` means there is more than one instance of each backend that tries to register itself. and you get them for `cpu` backend - so it's multiple copies of `tfjs-core` (or `tfjs` metapackage), not just `tfjs-backend-webgl` that's loading twice.

actual error `Error when getting WebGL context: Error: Cannot create a canvas in this context` comes from inside tfjs code during initialization of `webgl` backend:

```js
if (typeof OffscreenCanvas !== 'undefined' && webGLVersion === 2) {
  return new OffscreenCanvas(300, 150);
} else if (typeof document !== 'undefined') {
  return document.createElement('canvas');
} else {
  throw new Error('Cannot create a canvas in this context');
}
```
which pretty much can only fail if executed within a web worker as Firefox doesn't supprot `OffscreenCanvas` and DOM is only undefined inside web worker (or NodeJS that doesn't have DOM to start with, but that's a totally offtopic).

you said earlier you're not using web workers yourself - but it seems that `audio-ml-plugin` is using them and it tries to initialize backend inside a worker instead of just using it (which would work). But since backend is already initialized, error becomes non-fatal since worker can use it regardless of the initialization failure.

hope this helps...

**Comment by ost12666** [comment]
Thanks!

I said I don't use Web Worker for human because of the cons but for audio we do you web worker. I heard about Firefox limitations but didn't think it will be a problem with audio but I guess the model uses spectrograms which are images so it needs a canvas. 

Not sure what it means to initialize a backend since this is the code that runs on the worker to initialize the plugin:

import * as tf from '@tensorflow/tfjs';

 loadModel: async () => {
        model = await tf.loadLayersModel('../../models/audio/model.json');
        const arr = [makeArray(INPUT_SHAPE[1], INPUT_SHAPE[0], 0)];
        const input = tf.tensor(arr, [1, ...INPUT_SHAPE]);
        model.predict(input);
        return NUM_FRAMES;
    },

No sure what to do and if the audio stuff is using webgl or some fallback

**Comment by vladmandic** [comment]
Canvas is not used just for graphics.  How it works is that `tfjs` creates tiny canvas just to get WebGL context to it - without context, there is no way to upload shaders and commands to GPU (that's one of the reasons why I've created `humangl` so I can control creation of that canvas and context and re-use it as I want and not rely on internal creation inside `tfjs`).

And initialization is implicit if you're using tfjs metapackage as `import * as tf from '@tensorflow/tfjs';`
What does initialization to? Checks capabilities and registers actual operations. Since they are already registered, nothing bad happens (regardless if error is 'already registered' or `cannot create context).

**Comment by ost12666** [comment]
Ok thanks for your help!
