### ISSUE TITLE
Regarding Blazepose

### ISSUE THREAD

**Issue by ButzYung** [vladmandic/human#82]
I notice that you have added the support of Blazepose in your latest update. I tried it, but it didn't seem to work well with non-full-body tracking. I know that Blazepose has an upper-body-only model. I wonder if you have any plan to add that as an option.

**Comment by vladmandic** [comment]
>  it didn't seem to work well with non-full-body tracking

yup, exactly what i've noted in `wiki/models`

> I know that Blazepose has an upper-body-only model. I wonder if you have any plan to add that as an option.

yup again :)

**Comment by vladmandic** [comment]
i've added `blazepose-upper` model and published new version  
i don't think it's a really good model in my opinion, but still worth including  

btw, i could use help identifying keypoints - see `src/blazepose/annotations.ts` for details  

there are some 6 pairs that i haven't been able to quickly identify and model documentation is basically non-existent and anything that is actually published by mediapipe refers to a much older version of model that has a completely different output format

**Comment by ButzYung** [comment]
`blazepose-upper` works, but like what you said, the model isn't really good. It's better than the full model when used to detect only upper body, but still less accurate than PoseNet.

As for the annotations, I think 0-24 are just the same as the full model...?

I have come across the github of another guy who also has some projects on custom TFJS models.

https://github.com/terryky/tfjs_webgl_app

He has some blazepose demos as well, and they seem to yield better results. It's beyond my knowledge to understand the difference between his implementations and yours, but you may want to check it out.

**Comment by vladmandic** [comment]
i'm aware of it - he's using older version of `blazepose` model and manually analyzing strides  
newer version of `blazepose` model does not output strides, but keypoints directly  

i guess mediapipe team is still working on  the new version of blazepose as  
keypoint output is not nearly as good as manually parsing strides within model  

my guess is that the new approach will eventually catch-up  
and when it does, it looks quite promising. but for now, it is what it is - that's why i don't even enable it by default  

regarding annotations - could be, but i haven't been able to verify

**Comment by vladmandic** [comment]
btw, i've been playing a bit more with `blazepose` (full body variation) and it's actually extremely stable - but only if person is 100% in frame and actually in center of a frame. otherwise, there are false positives and score/presence values don't help.  

as a test, i've started feeding image through simple object detection model trained on coco dataset first to identify person and then crop the person out of the image (with some whitespace padding) and just run that through `blazepose` - works like a charm. but including object detection model and running `blazepose` through such pipeline is too intensive for standard usage.

**Comment by vladmandic** [comment]
since both `blazepose full` and `blazepose upper` models have been added, i'm closing this issue.
