### ISSUE TITLE
PoseNet ResNET is broken

### ISSUE THREAD

**Issue by ButzYung** [vladmandic/human#90]
I can't get the PoseNet ResNET model working anymore on the latest version of `human` (maybe it has been broken since certain update but I am not sure).

```
Uncaught (in promise) Error: Requested out of range element at 0,4,32.   Buffer shape=17,17,32
    at $t.get (tensor.ts:105)
    at Tae (decoders.ts:18)
    at Cae (decoders.ts:27)
    at decoders.ts:35
    at engine.ts:467
    at Fu.scopedRun (engine.ts:478)
    at Fu.tidy (engine.ts:465)
    at z (globals.ts:192)
    at z6 (decoders.ts:35)
    at U6 (decodePose.ts:84)
```

I notice that there are some changes to the config regarding `body`. `modelType` property is gone and `ResNet` support is not mentioned anymore.

**Comment by vladmandic** [comment]
sorry, it's been removed several versions ago and is no longer documented as supported.

`posenet-resnet` processing was pretty much separate from standard and maintaining both was a pain - i couldn't do many improvements i wanted to `posenet` processing because of it. especially since `resnet` variation was not included in human anyhow due to its size  

if the results with `resnet` variation were much better, i might keep it. but as it is, results were only marginally better.

i've recently implemented `blazepose` as alternative which is great but only in specific conditions - when person is fully visible and in the center of the frame.

i'm still looking for a good body model - `efficientpose` looks interesting so far

i'm closing this as will-not-fix
